<?php if (defined('AAM_KEY')) { ?>
    <div class="aam-feature" id="utilities-content">
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#utility-core" aria-controls="utility-core" role="tab" data-toggle="tab"><?php echo __('AAM Core', AAM_KEY); ?></a></li>
            <li role="presentation"><a href="#utility-post" aria-controls="utility-post" role="tab" data-toggle="tab"><?php echo __('Posts Access', AAM_KEY); ?></a></li>
            <li role="presentation"><a href="#utility-tools" aria-controls="utility-tools" role="tab" data-toggle="tab"><?php echo __('Tools', AAM_KEY); ?></a></li>
            <li role="presentation"><a href="#utility-miscellaneous" aria-controls="utility-miscellaneous" role="tab" data-toggle="tab"><?php echo __('Miscellaneous', AAM_KEY); ?></a></li>
        </ul>
        
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="utility-core">
                <table class="table table-striped table-bordered">
                    <tbody>
                        <?php foreach($this->getUtilityOptionList('core') as $id => $option) { ?>
                            <tr>
                                <td>
                                    <span class='aam-setting-title'><?php echo $option['title']; ?></span>
                                    <p class="aam-setting-description">
                                        <?php echo $option['descr']; ?>
                                    </p>
                                </td>
                                <td class="text-center">
                                    <input data-toggle="toggle" name="<?php echo $id; ?>" id="utility-<?php echo $id; ?>" <?php echo ($option['value'] ? 'checked' : ''); ?> type="checkbox" data-on="Enabled" data-off="Disabled" data-size="small" />
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div role="tabpanel" class="tab-pane" id="utility-post">
                <table class="table table-striped table-bordered">
                    <tbody>
                        <?php foreach($this->getUtilityOptionList('post') as $id => $option) { ?>
                            <tr>
                                <td>
                                    <span class='aam-setting-title'><?php echo $option['title']; ?></span>
                                    <p class="aam-setting-description">
                                        <?php echo $option['descr']; ?>
                                    </p>
                                </td>
                                <td class="text-center">
                                    <input data-toggle="toggle" name="<?php echo $id; ?>" id="utility-<?php echo $id; ?>" <?php echo ($option['value'] ? 'checked' : ''); ?> type="checkbox" data-on="Enabled" data-off="Disabled" data-size="small" />
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div role="tabpanel" class="tab-pane" id="utility-tools">
                <table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <td>
                                <span class='aam-setting-title'><?php echo __('Export AAM Settings', AAM_KEY); ?></span>
                                <p class="aam-setting-description">
                                    <?php echo sprintf(__('Export selected AAM settings to the file. For more information about this feature check %sHow to export and import AAM settings%s article.', AAM_KEY), '<a href="https://aamplugin.com/help/how-to-export-and-import-aam-settings" target="_blank">', '</a>'); ?>
                                </p>
                            </td>
                            <td>
                                <a href="#" class="btn btn-success btn-block" id="export-aam">Export</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class='aam-setting-title'><?php echo __('Import AAM Settings', AAM_KEY); ?></span>
                                <p class="aam-setting-description">
                                    <?php echo __('Import AAM settings from the file.', AAM_KEY); ?>
                                </p>
                            </td>
                            <td>
                                <div class="hidden"><input type="file" id="aam-import-file" /></div>
                                <a href="#" class="btn btn-warning btn-block" id="import-aam">Import</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class='aam-setting-title'><?php echo __('Clear Cache', AAM_KEY); ?></span>
                                <p class="aam-setting-description">
                                    <?php echo __('Clear all AAM cache.', AAM_KEY); ?>
                                </p>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-block" id="clear-cache">Clear</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class='aam-setting-title'><?php echo __('Clear All Settings', AAM_KEY); ?></span>
                                <p class="aam-setting-description">
                                    <?php echo __('Remove all the settings related to AAM from the database.', AAM_KEY); ?>
                                </p>
                            </td>
                            <td>
                                <a href="#clear-settings-modal" data-toggle="modal" class="btn btn-danger btn-block">Clear</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div role="tabpanel" class="tab-pane" id="utility-miscellaneous">
                <table class="table table-striped table-bordered">
                    <tbody>
                        <?php $misc = $this->getUtilityOptionList('miscellaneous'); ?>
                        <?php if (count($misc)) { ?>
                            <?php foreach($this->getUtilityOptionList('miscellaneous') as $id => $option) { ?>
                                <tr>
                                    <td>
                                        <span class='aam-setting-title'><?php echo $option['title']; ?></span>
                                        <p class="aam-setting-description">
                                            <?php echo $option['descr']; ?>
                                        </p>
                                    </td>
                                    <td class="text-center">
                                        <input data-toggle="toggle" name="<?php echo $id; ?>" id="utility-<?php echo $id; ?>" <?php echo ($option['value'] ? 'checked' : ''); ?> type="checkbox" data-on="Enabled" data-off="Disabled" data-size="small" />
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                                <tr>
                                    <td colspan="2" class="text-center"><?php echo __('No miscellaneous options found.', AAM_KEY); ?></td>
                                </tr>
                        <?php } ?>

                        <?php do_action('aam-post-utilities-setting'); ?>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="modal fade" id="clear-settings-modal" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title"><?php echo __('Clear all settings', AAM_KEY); ?></h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-center alert alert-danger text-larger"><?php echo __('All AAM settings will be removed.', AAM_KEY); ?></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" id="clear-settings"><?php echo __('Clear', AAM_KEY); ?></button>
                        <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Cancel', AAM_KEY); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php }